"""
CSV / Excel financial data ingester.

Reads the AI CFO Excel template (Field/Value/Description columns) or a flat
two-column CSV (field, value) and returns a dict ready for FinancialDataSchema.

Supported input formats:
  1. Excel template (.xlsx) — generated by generate_test_upload.py
       Column A: field_name  |  Column B: value  |  Column C: description (ignored)
  2. Flat CSV (.csv) — two-column:  field_name,value
  3. Wide CSV (.csv) — one row per company, one column per field (first row = headers)

Usage:
    from backend.ingestion.csv_ingester import ingest_file, ingest_excel, ingest_csv
    data = ingest_file("upload.xlsx", company_name="Acme", period="Q1 2026", currency="USD")
"""
from __future__ import annotations

import io
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

# Numeric fields in FinancialDataSchema that should be coerced to float
_NUMERIC_FIELDS = {
    "revenue", "cogs", "gross_profit", "operating_expenses", "rd_expense",
    "sg_a_expense", "ebitda", "depreciation_amortization", "depreciation",
    "ebit", "interest_expense", "pre_tax_income", "tax_provision", "net_income",
    "total_assets", "current_assets", "cash", "accounts_receivable",
    "inventory", "prepaid_expenses", "total_equity", "current_liabilities",
    "accounts_payable", "deferred_revenue", "total_debt", "long_term_debt",
    "goodwill", "rou_assets", "lease_liability", "allowance_for_credit_losses",
    "cash_from_operations", "capex", "free_cash_flow", "monthly_cash_burn",
    "operating_lease_expense", "shares_outstanding", "diluted_shares",
    "arr", "nrr_pct", "churn_rate_pct", "headcount",
    "rd_dev_capitalizable_pct",
    # Budget/Actuals variants
    "actuals_revenue", "actuals_cogs", "actuals_gross_profit", "actuals_ebitda",
    "actuals_rd_expense", "actuals_sg_a",
    "budget_revenue", "budget_cogs", "budget_gross_profit", "budget_ebitda",
    "budget_rd_expense", "budget_sg_a",
    # Historical quarters
    "hist_q1", "hist_q2", "hist_q3", "hist_q4", "hist_q5",
    "hist_q6", "hist_q7", "hist_q8", "hist_q9",
}

# String fields that should stay as strings
_STRING_FIELDS = {
    "company_name", "period", "currency", "jurisdiction", "listing_exchange",
    "industry", "revenue_recognition_policy", "goodwill_impairment_test_date",
    "interest_cash_flow_classification",
}

# Aliases for common column name variations (lowercase, underscored)
_ALIASES: Dict[str, str] = {
    "revenues":                  "revenue",
    "net_revenue":               "revenue",
    "total_revenue":             "revenue",
    "cost_of_goods_sold":        "cogs",
    "cost_of_revenue":           "cogs",
    "gross profit":              "gross_profit",
    "gross_margin":              "gross_profit",
    "opex":                      "operating_expenses",
    "operating_expense":         "operating_expenses",
    "r&d":                       "rd_expense",
    "research_and_development":  "rd_expense",
    "rd":                        "rd_expense",
    "sga":                       "sg_a_expense",
    "sg&a":                      "sg_a_expense",
    "selling_general_admin":     "sg_a_expense",
    "d&a":                       "depreciation_amortization",
    "depreciation_and_amortization": "depreciation_amortization",
    "interest":                  "interest_expense",
    "ebt":                       "pre_tax_income",
    "pretax_income":             "pre_tax_income",
    "income_tax":                "tax_provision",
    "taxes":                     "tax_provision",
    "net_profit":                "net_income",
    "earnings":                  "net_income",
    "assets":                    "total_assets",
    "total_current_assets":      "current_assets",
    "cash_and_equivalents":      "cash",
    "ar":                        "accounts_receivable",
    "receivables":               "accounts_receivable",
    "ap":                        "accounts_payable",
    "payables":                  "accounts_payable",
    "equity":                    "total_equity",
    "shareholders_equity":       "total_equity",
    "stockholders_equity":       "total_equity",
    "current_liab":              "current_liabilities",
    "deferred_rev":              "deferred_revenue",
    "debt":                      "total_debt",
    "shares":                    "shares_outstanding",
    "basic_shares":              "shares_outstanding",
    "diluted":                   "diluted_shares",
    "capex_spend":               "capex",
    "capital_expenditure":       "capex",
    "capital_expenditures":      "capex",
    "fcf":                       "free_cash_flow",
    "operating_cashflow":        "cash_from_operations",
    "operating_cash_flow":       "cash_from_operations",
    "burn_rate":                 "monthly_cash_burn",
    "arr_usd":                   "arr",
    "employees":                 "headcount",
    "headcount_total":           "headcount",
    "nrr":                       "nrr_pct",
    "net_revenue_retention":     "nrr_pct",
    "churn":                     "churn_rate_pct",
}


# ── Parsing helpers ───────────────────────────────────────────────────────────

def _normalise_key(raw: str) -> str:
    """Lower-case, strip, replace spaces/hyphens with underscores."""
    key = str(raw).strip().lower().replace(" ", "_").replace("-", "_")
    key = re.sub(r"[^a-z0-9_]", "", key)
    return _ALIASES.get(key, key)


def _parse_value(raw: Any) -> Any:
    """Strip currency formatting from a value; return float if numeric."""
    if raw is None or (isinstance(raw, str) and not raw.strip()):
        return None
    if isinstance(raw, (int, float)):
        return raw
    # Strip dollar signs, commas, percentage markers
    cleaned = re.sub(r"[$,%]", "", str(raw).strip().replace(",", ""))
    try:
        return float(cleaned)
    except ValueError:
        return str(raw).strip()


def _coerce_field(key: str, value: Any) -> Any:
    """Coerce a value to the expected type for its field."""
    if value is None:
        return None
    if key in _NUMERIC_FIELDS:
        try:
            return float(str(value).replace(",", "").replace("$", "").replace("%", ""))
        except (ValueError, TypeError):
            return None
    if key in _STRING_FIELDS:
        return str(value).strip()
    return _parse_value(value)


def _build_budget_actuals(flat: Dict[str, Any]) -> Dict[str, Any]:
    """
    Reconstruct actuals/budget dicts and historical_revenue list
    from flat field names like actuals_revenue, budget_cogs, hist_q1…
    """
    actuals = {}
    budget = {}
    hist = {}

    for key, val in list(flat.items()):
        if key.startswith("actuals_") and val is not None:
            sub = key[len("actuals_"):]
            actuals[sub] = float(val)
            del flat[key]
        elif key.startswith("budget_") and val is not None:
            sub = key[len("budget_"):]
            budget[sub] = float(val)
            del flat[key]
        elif re.match(r"^hist_q\d+$", key) and val is not None:
            idx = int(key[6:])
            hist[idx] = float(val)
            del flat[key]

    if actuals:
        flat["actuals"] = actuals
    if budget:
        flat["budget"] = budget
    if hist:
        flat["historical_revenue"] = [hist[i] for i in sorted(hist)]

    return flat


# ── Excel ingester ────────────────────────────────────────────────────────────

def ingest_excel(
    source: Union[str, bytes, io.BytesIO],
    company_name: Optional[str] = None,
    period: Optional[str] = None,
    currency: str = "USD",
) -> Dict[str, Any]:
    """
    Parse the AI CFO Excel template (Field / Value / Description columns).

    Args:
        source: file path, raw bytes, or BytesIO buffer
        company_name: override or provide company name if not in the file
        period: override or provide period
        currency: default currency if not in file

    Returns:
        flat dict ready for FinancialDataSchema(**result)
    """
    try:
        import openpyxl
    except ImportError as e:
        raise ImportError("openpyxl is required for Excel ingestion: pip install openpyxl") from e

    if isinstance(source, (str, Path)):
        wb = openpyxl.load_workbook(source, read_only=True, data_only=True)
    else:
        if isinstance(source, bytes):
            source = io.BytesIO(source)
        wb = openpyxl.load_workbook(source, read_only=True, data_only=True)

    ws = wb.active
    flat: Dict[str, Any] = {}

    for row in ws.iter_rows(values_only=True):
        if not row or row[0] is None:
            continue
        raw_key = str(row[0]).strip()
        if not raw_key or raw_key.upper() in (
            "FIELD", "INCOME STATEMENT", "BALANCE SHEET", "CASH FLOW",
            "EQUITY", "SAAS METRICS", "BUDGET VS ACTUALS", "HISTORICAL REVENUE",
            "AI CFO SYSTEM - FINANCIAL DATA TEMPLATE",
            "INSTRUCTIONS: FILL COLUMN B (BLUE CELLS). DO NOT EDIT COLUMN A OR C.",
        ):
            continue

        key = _normalise_key(raw_key)
        val = row[1] if len(row) > 1 else None
        coerced = _coerce_field(key, val)
        if coerced is not None:
            flat[key] = coerced

    wb.close()

    # Inject metadata overrides
    if company_name:
        flat["company_name"] = company_name
    if period:
        flat["period"] = period
    if "currency" not in flat:
        flat["currency"] = currency

    flat = _build_budget_actuals(flat)
    return flat


# ── CSV ingester ──────────────────────────────────────────────────────────────

def ingest_csv(
    source: Union[str, bytes, io.StringIO],
    company_name: Optional[str] = None,
    period: Optional[str] = None,
    currency: str = "USD",
) -> Dict[str, Any]:
    """
    Parse a CSV financial data file.

    Supports two formats:
    - Two-column (field_name, value): each row is one field
    - Wide format (header row + data row): one column per field

    Args:
        source: file path, raw bytes, or StringIO buffer

    Returns:
        flat dict ready for FinancialDataSchema(**result)
    """
    import csv

    if isinstance(source, (str, Path)):
        with open(source, newline="", encoding="utf-8") as f:
            text = f.read()
    elif isinstance(source, bytes):
        text = source.decode("utf-8", errors="replace")
    else:
        text = source.read()

    reader = csv.reader(io.StringIO(text))
    rows = [r for r in reader if any(c.strip() for c in r)]

    if not rows:
        raise ValueError("CSV file is empty")

    flat: Dict[str, Any] = {}

    # Detect format:
    # - Two-column: each row = (field_name, value); first cell is a known field
    # - Wide: first row = headers with 3+ columns; subsequent rows = data
    def _looks_like_two_column() -> bool:
        if not rows:
            return False
        max_cols = max(len(r) for r in rows)
        if max_cols > 2:
            return False  # wide format — has 3+ columns
        # 2 items per row: check if first cell of first row is a known field/alias
        first_key = _normalise_key(rows[0][0])
        return (
            first_key in _NUMERIC_FIELDS
            or first_key in _STRING_FIELDS
            or rows[0][0].strip() in _ALIASES
            or first_key in _ALIASES
        )

    if _looks_like_two_column():
        # Two-column format: field_name, value
        for row in rows:
            if len(row) < 2:
                continue
            key = _normalise_key(row[0])
            coerced = _coerce_field(key, row[1])
            if coerced is not None and key:
                flat[key] = coerced
    else:
        # Wide format: first row = headers, second (or more) rows = values
        headers = [_normalise_key(h) for h in rows[0]]
        if len(rows) < 2:
            raise ValueError("Wide-format CSV must have at least one data row")
        # Use first data row
        data_row = rows[1]
        for header, val in zip(headers, data_row):
            if not header:
                continue
            coerced = _coerce_field(header, val)
            if coerced is not None:
                flat[header] = coerced

    # Inject metadata overrides
    if company_name:
        flat["company_name"] = company_name
    if period:
        flat["period"] = period
    if "currency" not in flat:
        flat["currency"] = currency

    flat = _build_budget_actuals(flat)
    return flat


# ── Unified entry point ───────────────────────────────────────────────────────

def ingest_file(
    path: Union[str, Path],
    company_name: Optional[str] = None,
    period: Optional[str] = None,
    currency: str = "USD",
) -> Dict[str, Any]:
    """
    Auto-detect file type and ingest.

    Returns a dict ready for:
        from backend.schemas.financial import FinancialDataSchema
        schema = FinancialDataSchema(**ingest_file("upload.xlsx"))
    """
    path = Path(path)
    suffix = path.suffix.lower()

    if suffix in (".xlsx", ".xls"):
        return ingest_excel(str(path), company_name=company_name, period=period, currency=currency)
    elif suffix in (".csv", ".tsv", ".txt"):
        return ingest_csv(str(path), company_name=company_name, period=period, currency=currency)
    else:
        raise ValueError(f"Unsupported file type: {suffix}. Expected .xlsx, .xls, or .csv")


def ingest_bytes(
    data: bytes,
    filename: str,
    company_name: Optional[str] = None,
    period: Optional[str] = None,
    currency: str = "USD",
) -> Dict[str, Any]:
    """
    Ingest from raw bytes (e.g. from a Streamlit file_uploader).

    Args:
        data: raw file bytes
        filename: original filename — used to detect format (.xlsx vs .csv)
    """
    suffix = Path(filename).suffix.lower()
    if suffix in (".xlsx", ".xls"):
        return ingest_excel(data, company_name=company_name, period=period, currency=currency)
    elif suffix in (".csv", ".tsv", ".txt"):
        return ingest_csv(data, company_name=company_name, period=period, currency=currency)
    else:
        raise ValueError(f"Unsupported file type: {suffix}")
